// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/MustafaTheEngineer/review_board/internal/database"
)

type Mutation struct {
}

type NewUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Query struct {
}

type RegisterUserResponse struct {
	Message string         `json:"message"`
	User    *database.User `json:"user"`
}

type SignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignInResponse struct {
	Message string         `json:"message"`
	User    *database.User `json:"user"`
}

type TokenValidationResponse struct {
	Valid bool `json:"valid"`
}
