// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/MustafaTheEngineer/review_board/internal/database"
)

type ConfirmUserInput struct {
	ConfirmationCode string `json:"confirmationCode"`
}

type ConfirmUserResponse struct {
	Message string         `json:"message"`
	User    *database.User `json:"user"`
}

type CreateItemRequest struct {
	Title       string   `json:"title"`
	Description *string  `json:"description,omitempty"`
	Amount      float64  `json:"amount"`
	Tags        []string `json:"tags"`
}

type CreateItemResponse struct {
	Item *database.Item `json:"item"`
	Tags []string       `json:"tags"`
}

type Mutation struct {
}

type NewUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Query struct {
}

type RegisterUserResponse struct {
	Message string         `json:"message"`
	User    *database.User `json:"user"`
}

type SetUsernameResponse struct {
	Message string         `json:"message"`
	User    *database.User `json:"user"`
}

type SignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignInResponse struct {
	Message string         `json:"message"`
	User    *database.User `json:"user"`
}

type TagsInput struct {
	Limit  *int32  `json:"limit,omitempty"`
	Offset *int32  `json:"offset,omitempty"`
	Like   *string `json:"like,omitempty"`
}

type TokenValidationResponse struct {
	User *database.User `json:"user"`
}
