// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tag.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const insertTag = `-- name: InsertTag :one
INSERT INTO tags (id, created_by_user_id, name)
VALUES ($1, $2, $3)
RETURNING id, created_by_user_id, name, created_at, updated_at
`

type InsertTagParams struct {
	ID              uuid.UUID     `json:"id"`
	CreatedByUserID uuid.NullUUID `json:"createdByUserId"`
	Name            string        `json:"name"`
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, insertTag, arg.ID, arg.CreatedByUserID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.CreatedByUserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectItemTags = `-- name: SelectItemTags :many
SELECT t.id, t.name
FROM tags t
INNER JOIN item_tags it ON t.id = it.tag_id
WHERE it.item_id = $1
`

type SelectItemTagsRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) SelectItemTags(ctx context.Context, itemID uuid.UUID) ([]SelectItemTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, selectItemTags, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectItemTagsRow
	for rows.Next() {
		var i SelectItemTagsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectTagByName = `-- name: SelectTagByName :one
SELECT id, created_by_user_id, name, created_at, updated_at FROM tags WHERE name = $1
`

func (q *Queries) SelectTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, selectTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.CreatedByUserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
